print('|||Programa que mosta a tabuada de um número|||')
nt = int(input('Digite um Número para ver sua Tabuada:'))
print(f'A tabuada de {nt} é:')
print('-' * 12)
print(f'{nt} x 1 = {nt * 1}')
print(f'{nt} x 2 = {nt * 2}')
print(f'{nt} x 3 = {nt * 3}')
print(f'{nt} x 4 = {nt * 4}')
print(f'{nt} x 5 = {nt * 5}')
print(f'{nt} x 6 = {nt * 6}')
print(f'{nt} x 7 = {nt * 7}')
print(f'{nt} x 8 = {nt * 8}')
print(f'{nt} x 9 = {nt * 9}')
print(f'{nt} x 10 = {nt * 10}')
print('-' * 12)
